#!/usr/bin/env bash
#
# 数据建模模块全自动化端到端测试
#
# 从零开始: 登录 → 建连接 → 测试连接 → 浏览表 → 生成草稿 → 建模型 →
# 发布 → 预览 → 建数据组 → 权限过滤 → 回滚 → 清理
#
# 前置条件:
#   - WeKnora 后端在 8080 运行, CUBE_ENABLE=true
#   - Cube 容器在 4000 运行 (docker compose -f ... -f docker-compose.cube.yml up -d cube)
#   - 一个 MySQL 业务库可达 (默认用 cube-mcp 的 mock 库 erp_clt@13306)
#   - 有一个管理员账户可登录
#
# 用法:
#   EMAIL=xxx PASS=xxx bash deploy/cube/test-semantic-e2e.sh
#
# 可选环境变量:
#   DB_HOST (默认 172.18.0.1)  DB_PORT (默认 13306)
#   DB_USER (默认 <your_db_user>)        DB_PASS (<your_db_password>)
#   DB_NAME (默认 erp_clt)
#   TABLE_SCHEMA (默认 erp_clt) TABLE_NAME (默认 sn_list)
#   CLEANUP (默认 true, 测完清理创建的资源)
set -euo pipefail

B="http://127.0.0.1:8080/api/v1/semantic"
EMAIL="${EMAIL:?need EMAIL}"; PASS="${PASS:?need PASS}"
DB_HOST="${DB_HOST:-172.18.0.1}"
DB_PORT="${DB_PORT:-13306}"
DB_USER="${DB_USER:-<your_db_user>}"
DB_PASS="${DB_PASS:-<your_db_password>}"
DB_NAME="${DB_NAME:-erp_clt}"
TABLE_SCHEMA="${TABLE_SCHEMA:-erp_clt}"
TABLE_NAME="${TABLE_NAME:-sn_list}"
CLEANUP="${CLEANUP:-true}"

# 唯一前缀避免与真实数据冲突
PREFIX="e2e_$(date +%s)"
CONN_NAME="${PREFIX}_conn"
MODEL_NAME="${PREFIX}_model"
GROUP_NAME="${PREFIX}_group"

pass=0; fail=0
check() {
  local name="$1" cond="$2"
  if eval "$cond" 2>/dev/null; then
    echo "  PASS  $name"; pass=$((pass+1))
  else
    echo "  FAIL  $name"; fail=$((fail+1))
  fi
}

echo "=== 数据建模端到端测试 (prefix=$PREFIX) ==="
echo ""

# ---- 登录 ----
echo "[1/12] 登录"
TOKEN=$(curl -s -X POST http://127.0.0.1:8080/api/v1/auth/login \
  -H 'Content-Type: application/json' \
  -d "{\"email\":\"$EMAIL\",\"password\":\"$PASS\"}" \
  | python3 -c "import sys,json; print(json.load(sys.stdin).get('token',''))")
check "login success" "[ ${#TOKEN} -gt 50 ]"
H1="Authorization: Bearer $TOKEN"; H2="X-Tenant-ID: 10001"; H3="Content-Type: application/json"

# 拿 user id (后续建数据组要用)
USER_ID=$(curl -s http://127.0.0.1:8080/api/v1/auth/me -H "$H1" -H "$H2" \
  | python3 -c "import sys,json; print(json.load(sys.stdin).get('data',{}).get('user',{}).get('id',''))" 2>/dev/null || echo "")

# ---- 模块健康 ----
echo "[2/12] 模块健康检查"
INFO=$(curl -s $B/info -H "$H1" -H "$H2")
check "module enabled" "[ \"$(echo "$INFO" | python3 -c "import sys,json;print(json.load(sys.stdin)['enabled'])")\" = 'True' ]"
check "cube ready" "[ \"$(echo "$INFO" | python3 -c "import sys,json;print(json.load(sys.stdin)['cube_ready'])")\" = 'True' ]"
check "guided types = 4" "[ $(echo "$INFO" | python3 -c "import sys,json;print(len(json.load(sys.stdin)['guided_types']))") -eq 4 ]"

# ---- 建连接 ----
echo "[3/12] 建数据源连接"
CONN_ID=$(curl -s -X POST $B/connections -H "$H1" -H "$H2" -H "$H3" \
  -d "{\"name\":\"$CONN_NAME\",\"title\":\"E2E Test\",\"type\":\"mysql\",\"host\":\"$DB_HOST\",\"port\":$DB_PORT,\"database\":\"$DB_NAME\",\"username\":\"$DB_USER\",\"password\":\"$DB_PASS\"}" \
  | python3 -c "import sys,json; print(json.load(sys.stdin).get('id',''))" 2>/dev/null || echo "")
check "connection created" "[ ${#CONN_ID} -gt 10 ]"

# 连接不应回传密码
CONN_RESP=$(curl -s $B/connections/$CONN_ID -H "$H1" -H "$H2")
check "no password in response" "[ $(echo "$CONN_RESP" | grep -c '\"password\"') -eq 0 ]"
# 非敏感参数应回填
check "host pre-filled" "[ \"$(echo "$CONN_RESP" | python3 -c "import sys,json;print(json.load(sys.stdin).get('host',''))")\" = '$DB_HOST' ]"

# ---- 测试连接 ----
echo "[4/12] 测试连接"
TEST=$(curl -s -X POST "$B/connections/$CONN_ID/test" -H "$H1" -H "$H2" -H "$H3" -d '{}')
check "connection test ok" "[ \"$(echo "$TEST" | python3 -c "import sys,json;print(json.load(sys.stdin).get('test',{}).get('ok',''))")\" = 'True' ]"

# ---- 表结构浏览 ----
echo "[5/12] 表结构浏览"
TABLES=$(curl -s "$B/connections/$CONN_ID/tables" -H "$H1" -H "$H2")
TABLE_COUNT=$(echo "$TABLES" | python3 -c "import sys,json;print(len(json.load(sys.stdin).get('tables',[])))" 2>/dev/null || echo 0)
check "tables non-empty" "[ $TABLE_COUNT -gt 0 ]"

# ---- 草稿生成 ----
echo "[6/12] 草稿生成"
DRAFT=$(curl -s "$B/connections/$CONN_ID/draft?schema=$TABLE_SCHEMA&table=$TABLE_NAME" -H "$H1" -H "$H2")
DRAFT_YAML=$(echo "$DRAFT" | python3 -c "import sys,json;print(json.load(sys.stdin).get('yaml',''))" 2>/dev/null || echo "")
check "draft generated" "[ ${#DRAFT_YAML} -gt 50 ]"
check "draft has count measure" "[ $(echo "$DRAFT_YAML" | grep -c 'count') -ge 1 ]"
check "draft has soft-delete filter" "[ $(echo "$DRAFT_YAML" | grep -c 'deleted_at') -ge 0 ]"

# ---- 建模型 ----
echo "[7/12] 建模型"
# 用草稿 YAML 但改名为我们的测试名
DRAFT_MODIFIED=$(echo "$DRAFT_YAML" | sed "s/name: $TABLE_NAME/name: $MODEL_NAME/" | sed "s/title: $TABLE_NAME/title: E2E Test Model/")
MODEL_PAYLOAD=$(python3 -c "
import json
print(json.dumps({'name':'$MODEL_NAME','title':'E2E Test Model','description':'Auto-generated by e2e test',
  'connection_id':'$CONN_ID','kind':'cube','draft_yaml':'''$DRAFT_MODIFIED''','allowed_groups':[]}))
")
MODEL_ID=$(curl -s -X POST $B/models -H "$H1" -H "$H2" -H "$H3" -d "$MODEL_PAYLOAD" \
  | python3 -c "import sys,json;print(json.load(sys.stdin).get('id',''))" 2>/dev/null || echo "")
check "model created" "[ ${#MODEL_ID} -gt 10 ]"
check "model status draft" "[ \"$(curl -s $B/models/$MODEL_ID -H "$H1" -H "$H2" | python3 -c "import sys,json;print(json.load(sys.stdin).get('status',''))")\" = 'draft' ]"

# ---- 发布 ----
echo "[8/12] 发布模型"
PUB=$(curl -s -X POST "$B/models/$MODEL_ID/publish" -H "$H1" -H "$H2" -H "$H3" -d '{"note":"e2e test publish"}')
check "publish success" "[ \"$(echo "$PUB" | python3 -c "import sys,json;print(json.load(sys.stdin).get('status',''))")\" = 'published' ]"
PUB_VERSION=$(echo "$PUB" | python3 -c "import sys,json;print(json.load(sys.stdin).get('version',0))" 2>/dev/null || echo 0)
check "version >= 1" "[ $PUB_VERSION -ge 1 ]"

# ---- 预览 ----
echo "[9/12] 数据预览"
PREVIEW=$(curl -s -X POST "$B/models/$MODEL_ID/preview" -H "$H1" -H "$H2" -H "$H3" \
  -d "{\"measures\":[\"${MODEL_NAME}.count\"],\"limit\":3}")
PREVIEW_ROWS=$(echo "$PREVIEW" | python3 -c "import sys,json;print(len(json.load(sys.stdin).get('data',[])))" 2>/dev/null || echo 0)
check "preview returns data" "[ $PREVIEW_ROWS -ge 1 ]"

# ---- 建数据组 + 权限 ----
echo "[10/12] 数据组与权限"
GROUP_ID=$(curl -s -X POST $B/groups -H "$H1" -H "$H2" -H "$H3" \
  -d "{\"name\":\"$GROUP_NAME\",\"title\":\"E2E Group\",\"description\":\"test group\"}" \
  | python3 -c "import sys,json;print(json.load(sys.stdin).get('id',''))" 2>/dev/null || echo "")
check "group created" "[ ${#GROUP_ID} -gt 10 ]"

if [ -n "$USER_ID" ]; then
  curl -s -X PUT "$B/groups/$GROUP_ID/members" -H "$H1" -H "$H2" -H "$H3" \
    -d "{\"user_ids\":[\"$USER_ID\"]}" > /dev/null 2>&1
  check "members set" true
fi

# 更新模型授权给这个组
curl -s -X PUT "$B/models/$MODEL_ID" -H "$H1" -H "$H2" -H "$H3" \
  -d "{\"allowed_groups\":[\"$GROUP_NAME\"]}" > /dev/null 2>&1
# 重新发布使权限生效
curl -s -X POST "$B/models/$MODEL_ID/publish" -H "$H1" -H "$H2" -H "$H3" -d '{"note":"add group"}' > /dev/null 2>&1

# meta 应能看到 (用户在组里)
META_COUNT=$(curl -s $B/meta -H "$H1" -H "$H2" \
  | python3 -c "import sys,json;print(len(json.load(sys.stdin).get('cubes',[])))" 2>/dev/null || echo 0)
check "meta visible after group auth" "[ $META_COUNT -ge 1 ]"

# ---- 回滚 ----
echo "[11/12] 版本回滚"
# v1 的 id
V1_ID=$(curl -s "$B/models/$MODEL_ID/versions" -H "$H1" -H "$H2" \
  | python3 -c "
import sys,json
vs = json.load(sys.stdin).get('versions',[])
v1 = [v for v in vs if v['version']==1]
print(v1[0]['id'] if v1 else '')
" 2>/dev/null || echo "")
if [ -n "$V1_ID" ]; then
  RB=$(curl -s -X POST "$B/models/$MODEL_ID/rollback" -H "$H1" -H "$H2" -H "$H3" -d "{\"version_id\":\"$V1_ID\"}")
  check "rollback success" "[ \"$(echo "$RB" | python3 -c "import sys,json;print(json.load(sys.stdin).get('status',''))")\" = 'published' ]"
else
  check "rollback (no v1 found)" false
fi

# ---- 清理 ----
echo "[12/12] 清理"
if [ "$CLEANUP" = "true" ]; then
  # 下线模型再删
  curl -s -X POST "$B/models/$MODEL_ID/unpublish" -H "$H1" -H "$H2" > /dev/null 2>&1
  curl -s -X DELETE "$B/models/$MODEL_ID" -H "$H1" -H "$H2" > /dev/null 2>&1
  curl -s -X DELETE "$B/connections/$CONN_ID" -H "$H1" -H "$H2" > /dev/null 2>&1
  curl -s -X DELETE "$B/groups/$GROUP_ID" -H "$H1" -H "$H2" > /dev/null 2>&1
  check "cleanup done" true
else
  echo "  (cleanup skipped)"; check "cleanup skipped" true
fi

# ---- 审计 ----
AUDIT_COUNT=$(curl -s $B/audit -H "$H1" -H "$H2" \
  | python3 -c "import sys,json;print(len(json.load(sys.stdin).get('audit_logs',[])))" 2>/dev/null || echo 0)
check "audit logs recorded" "[ $AUDIT_COUNT -ge 1 ]"

echo ""
echo "==============================="
echo "PASS=$pass FAIL=$fail"
[ $fail -eq 0 ] && echo "ALL GREEN ✅" || echo "HAS FAILURES ❌"
